# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-08-21 07:12
from __future__ import unicode_literals

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='\u8bf7\u5728\u6b64\u8f93\u5165\u6807\u9898', max_length=30, verbose_name='\u6807\u9898')),
                ('shortcontent', models.TextField(default='\u8bf7\u5728\u6b64\u8f93\u5165\u6897\u6982', max_length=100, verbose_name='\u77ed\u6897\u6982')),
                ('content', DjangoUeditor.models.UEditorField(blank=True, default='', verbose_name='\u5185\u5bb9')),
                ('user_name', models.CharField(default='\u533f\u540d', max_length=20, verbose_name='\u4f5c\u8005')),
                ('kind', models.CharField(choices=[('python', 'python'), ('c++', 'c++'), ('java', 'java'), ('javascript', 'javascript'), ('html', 'html'), ('css', 'css'), ('linux', 'linux')], default=('python', 'python'), max_length=20, verbose_name='\u6587\u7ae0\u7c7b\u578b')),
                ('createtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-createtime'],
                'verbose_name': '\u535a\u5ba2\u6587\u7ae0',
                'verbose_name_plural': '\u535a\u5ba2\u6587\u7ae0',
            },
        ),
    ]
